export const ActionTypes = {
    FETCH_MUNICIPIOS: 'FETCH_MUNICIPIOS',
    FETCH_ESTADOS: 'FETCH_ESTADOS',
    SET_ESTADOS: 'SET_PRODUCTS',
    SET_MUNICIPIOS: 'SET_MUNICIPIOS',
    SELECTED_MUNICIPIO: 'SELECTED_MUNICIPIO',
}